services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80" # Map port 8000 on your local machine to port 80 in the container
    volumes:
      - .:/Users/vaibhavi/solidcomp/order-management # Mount your local project directory to the container
      - ./storage:/Users/vaibhavi/solidcomp/order-management/storage # Persist storage folder
    environment:
      - APACHE_DOCUMENT_ROOT=/Users/vaibhavi/solidcomp/order-management/public # Point Apache to Laravel's public folder
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data:
